services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123password
      POSTGRES_DB: JWTSecurity
    ports:
      - "5432:5432"
